# Generated by Django 5.1.4 on 2024-12-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafs', '0003_alter_category_options_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryitem',
            name='dimensions',
            field=models.CharField(default='', max_length=80, verbose_name='Габариты'),
        ),
    ]
