# Generated by Django 5.1.4 on 2024-12-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafs', '0004_categoryitem_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryitem',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='height',
            field=models.PositiveIntegerField(default=0, help_text='Введите высоту в мм.', verbose_name='Высота (мм)'),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='length',
            field=models.PositiveIntegerField(default=0, help_text='Введите длину в мм.', verbose_name='Длина (мм)'),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='width',
            field=models.PositiveIntegerField(default=0, help_text='Введите ширину в мм.', verbose_name='Ширина (мм)'),
        ),
    ]
