# Generated by Django 5.1.4 on 2024-12-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafs', '0005_remove_categoryitem_dimensions_categoryitem_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='height',
            field=models.PositiveIntegerField(help_text='Введите высоту в мм.', verbose_name='Высота (мм)'),
        ),
        migrations.AlterField(
            model_name='categoryitem',
            name='length',
            field=models.PositiveIntegerField(help_text='Введите длину в мм.', verbose_name='Длина (мм)'),
        ),
        migrations.AlterField(
            model_name='categoryitem',
            name='width',
            field=models.PositiveIntegerField(help_text='Введите ширину в мм.', verbose_name='Ширина (мм)'),
        ),
    ]
