# Generated by Django 5.1.4 on 2024-12-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafs', '0006_alter_categoryitem_height_alter_categoryitem_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryitem',
            name='height',
        ),
        migrations.RemoveField(
            model_name='categoryitem',
            name='length',
        ),
        migrations.RemoveField(
            model_name='categoryitem',
            name='width',
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='dimensions',
            field=models.CharField(default='', max_length=80, verbose_name='Габариты'),
        ),
    ]
